language: android
jdk: oraclejdk8
dist: trusty
sudo: true
android:
  components:
    - platform-tools
    - tools
    - build-tools-29.0.3
    - android-29
    - android-28
cache:
  - bundler
branches:
  only:
  - master
  - "/^stable-.*$/"
before_install:
- sudo apt-get install rvm=2.7.2
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrclicense
- git config --global user.name "Travis CI"
- git config --global user.email "tcisagebio@sagebase.org"
install:
- gem install bundler -v 1.17.2
- bundle install
script:
- ./travis/build.sh
